### ISSUE TITLE
Make http_get_basic_data()

### ISSUE THREAD

**Issue by thecodewizard** [nickdhondt/dungeons-and-dragons#28]
make a http page that will get the basic user data from the server and pass it with JSON to the client.
This page will get the data for all the users.

**Comment by nickdhondt** [comment]
@thecodewizard The basic data needs to be sent using the stream. So the http_get_basic_data() function could be in the functions.php file (and http_get_basic_data() would use timestamp to enable it to send when needed (real time)) a page http_get_basic_data.php will not be needed (since stream_push_events.php should do this.)
